package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "jgit-http-apache",
    exports = ["@jgit_http_apache//jar"],
)

java_library(
    name = "jgit-lfs",
    exports = ["@jgit_lfs//jar"],
)

java_library(
    name = "jgit-lfs-server",
    exports = ["@jgit_lfs_server//jar"],
)
