include_defs('//bucklets/maven_jar.bucklet')

VER = '2.14-SNAPSHOT'
REPO = MAVEN_LOCAL

maven_jar(
  name = 'plugin-api',
  id = 'com.google.gerrit:gerrit-plugin-api:' + VER,
  attach_source = False,
  repository = REPO,
  license = 'Apache2.0',
)
